site_name: Virtui Manager Documentation
site_url: https://aginies.github.io/virtui-manager/
site_description: The next-generation terminal-based management solution for QEMU/KVM virtualization.
site_author: aginies
repo_url: https://github.com/aginies/virtui-manager
repo_name: aginies/virtui-manager

docs_dir: documentation/manual
site_dir: docs/manual

theme:
  name: material
  logo: images/virtui-manager_logo_notext_inverted.png
  palette:
    scheme: slate
    primary: light green
    accent: teal
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

extra_css:
  - style.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Manual:
    - Management Window: main_window.md
    - VM Configuration: vm_configuration.md
    - VM Actions: vm_actions.md
    - Virtui Remote Viewer: remote_viewer.md
    - Web Console: web_console.md
    - Selection & Filtering: selection.md
    - Bulk Operations: bulk_ops.md
    - Command Line Interface: cli.md
    - App Configuration: app_configuration.md
    - App Installation: app_installation.md
    - Installation: installation.md
