site_name: VirtUI Manager Documentation
site_url: https://aginies.github.io/virtui-manager/
site_description: The next-generation terminal-based management solution for QEMU/KVM virtualization.
site_author: aginies
repo_url: https://github.com/aginies/virtui-manager
repo_name: aginies/virtui-manager

docs_dir: documentation/manual
site_dir: docs/manual

theme:
  name: material
  logo: images/virtui-manager_logo_notext_inverted.png
  palette:
    scheme: slate
    primary: light green
    accent: teal
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.tracking
    - content.code.copy
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github

extra_css:
  - style.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Manual:
    - Introduction: introduction.md
    - VirtUI Manager Installation: app_installation.md
    - Management Main Window: main_window.md
    - VirtUI Manager Configuration: app_configuration.md
    - Virtual Machine Configuration: vm_configuration.md
    - Control Virtual Machine: vm_actions.md
    - Selection & Filtering: selection.md
    - Bulk Operations: bulk_ops.md
    - Virtual Machine Migration: migration.md
    - Remote Web Console (VM): web_console.md
    - Virtual Machine Installation: installation.md
    - Virtui Remote Viewer: remote_viewer.md
    - VirtUI Manager CMD: cli.md
    - Debugging and Statistics: debugging_and_statistics.md
